@PORT = 8080
@URL = http://127.0.0.1
@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3ODU0NjU5NDksInN1YiI6IjAxOWZhODBlLTVjYTQtNzg0MS05YjdkLTc3ZDBlNzY5ZGJlYiIsImVtYWlsIjoibWZsb3JpYWNoQGV4YW1wbGUuY29tIn0.e1WtOnSZCzSdXhUpjISWEuvqLrJlASapvMroyQo8pSA
@EMAIL = "mfloriach@example.com"
@PASSWORD = "xxxxxxxxret"
###

GET  {{URL}}:{{PORT}}/api/v1/health
Content-Type: application/json

###

POST {{URL}}:{{PORT}}/api/v1/auth/sign_up
Content-Type: application/json

{
    "password": {{PASSWORD}},
    "username": "marti",
    "email": {{EMAIL}}
}

###

POST {{URL}}:{{PORT}}/api/v1/auth/sign_in
Content-Type: application/json

{
    "password": {{PASSWORD}},
    "email": {{EMAIL}}
}

###

POST  {{URL}}:{{PORT}}/api/v1/events/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "Test Event",
    "description": "This is a test event",
    "capacity": 5
}

###

POST  {{URL}}:{{PORT}}/api/v1/events/019fa80e-ba16-7c93-8e2b-e16528bac777/reservations
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "seats": 1
}

###

GET  {{URL}}:{{PORT}}/api/v1/reservations/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###

GET  {{URL}}:{{PORT}}/api/v1/events/?event_at_gte=sdkfh
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


###

POST  {{URL}}:{{PORT}}/api/v1/reservations/paied
Content-Type: application/json

{
    "reservation_id": "019fabdd-90e0-76c2-ad64-b201543ea86c",
    "user_id": "019fa80e-5ca4-7841-9b7d-77d0e769dbeb",
    "payment_id": "e7b6a2c7-f1e0-4d6b-b8b4-29d65d8f1d6d",
    "status": "succeeded"
}