@PORT = 8080
@URL = http://127.0.0.1
@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3ODcyMTMyODYsInN1YiI6IjAxYTAwMzE2LTVlOWEtNzI2Mi1hNWFhLTExNjQyOTBiNTVmMSIsImVtYWlsIjoibWZsb3JpYWNoQGV4YW1wbGUuY29tIn0.uNIEhBltA-GHcw6_wn2VAlgszgFGYAvLYYbcsFE57Cc
@EMAIL = "mfloriach@example.com"
@PASSWORD = "xxxxxxxxret"
###

GET  {{URL}}:{{PORT}}/api/v1/health
Content-Type: application/json

###

POST {{URL}}:{{PORT}}/api/v1/auth/sign_up
Content-Type: application/json

{
    "password": {{PASSWORD}},
    "username": "marti",
    "email": {{EMAIL}}
}

###

POST {{URL}}:{{PORT}}/api/v1/auth/sign_in
Content-Type: application/json

{
    "password": {{PASSWORD}},
    "email": {{EMAIL}}
}

###

POST  {{URL}}:{{PORT}}/api/v1/events/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
Idempotency-Key: 1234567895600

{
    "name": "Test Event7",
    "description": "This is a test event",
    "capacity": 59
}

###

POST  {{URL}}:{{PORT}}/api/v1/events/01a00132-d21e-7353-9d60-851e468ed021/reservations
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
Idempotency-Key: 1

{
    "seats": 1
}

###

GET  {{URL}}:{{PORT}}/api/v1/reservations/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###

GET  {{URL}}:{{PORT}}/api/v1/events/?event_at_gte=sdkfh
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


###

POST  {{URL}}:{{PORT}}/api/v1/reservations/paied
Content-Type: application/json

{
    "reservation_id": "019fabdd-90e0-76c2-ad64-b201543ea86c",
    "user_id": "019fa80e-5ca4-7841-9b7d-77d0e769dbeb",
    "payment_id": "e7b6a2c7-f1e0-4d6b-b8b4-29d65d8f1d6d",
    "status": "succeeded"
}