[package]
name = "rsv"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/bin/api.rs"
name = "api"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.9.0", features = ["runtime-async-std", "postgres", "uuid", "chrono"] }
config = "0.15.24"
dotenvy = "0.15.7"
uuid = { version = "1.23", features = ["v7", "serde", "std", "fast-rng"] }
chrono = {version = "0.4", features = ["serde"]}
env_logger = "0.11.11"
log = "0.4.33"
tracing = "0.1.44"
tracing-bunyan-formatter = "0.3.10"
tracing-subscriber = {version = "0.3.23", features = ["registry", "env-filter", "json"]}
tracing-log = "0.2.0"
secrecy = { version = "0.8",  features = ["serde"]}
tracing-actix-web = "0.7.22"
validator = { "version" = "0.20.0", features = ["derive"]}
actix-web-validator = "7.0.0"
reqwest = "0.11"
argon2 = "0.5.3"
jsonwebtoken = { "version" = "10.4.0", default-features = false, features = ["rust_crypto"] }
envy = "0.4.2"
redis = {"version" = "1.3.0", features = ["tokio-comp"]}
rdkafka = {"version" = "0.39.0", features = ["cmake-build"]}
futures = "0.3.32"
strum_macros = "0.28.0"
struct-field-names-as-array = "0.3.0"
thiserror = "2.0.18"
anyhow = "1.0.103"
serde_json = "1.0.150"
rslock = {"version" = "0.7.4", features = ["tokio-comp"] }
actix-http = "3.13.1"
testcontainers = "0.27.3"
testcontainers-modules = {"version" = "0.15.0", features = ["postgres", "redis"]}
futures-util = "0.3.33"
async-trait = "0.1.91"
async-channel = "2.5.0"

[dev-dependencies]
reqwest = "0.11"
