services:
  
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: 128mb
    logging:
      driver: "none"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    logging:
      driver: "none"

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://127.0.0.1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CFG_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data

  delay_queue:
    build: .
    command: ["/app/delay_queue"]
    depends_on:
      - kafka
      - db
    # environment:
    #   - DATABASE_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}
    #   - KAFKA_BROKER: kafka:9092
    #   - KAFKA_TOPIC: reservation.expire
    #   - KAFKA_GROUP_ID: reservation_expiring

  reservation_expirations:
    build: .
    command: ["/app/reservation_expiration"]
    depends_on:
      - kafka
      - db
    # environment:
    #   - KAFKA_BROKER_PRODUCER: kafka:9092
    #   - KAFKA_TOPIC_PRODUCER: reservation.expire
    #   - KAFKA_GROUP_ID_PRODUCER: reservation_expiring
    #   - KAFKA_BROKER_CONSUMER: kafka:9092
    #   - KAFKA_TOPIC_CONSUMER: reservation.delay
    #   - KAFKA_GROUP_ID_CONSUMER: reservation_expiring

volumes:
  pgdata:
  kafka-data:
